[project]
name = "sales_pipeline"
version = "0.1.0"
description = "Pipeline Spark de ventes"
authors = [{name = "Briac Six"}]
dependencies = [
  "pyspark",
  "pyyaml"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
